#!/usr/bin/env python3
# Copyright 2026 Junbo Zheng
# SPDX-License-Identifier: Apache-2.0
"""Generate cli_config.h or savedefconfig from Kconfig .config file."""

import os
import sys

import kconfiglib


def genconfig(kconf, output):
    """Generate cli_config.h header."""

    kconf.write_autoconf(output)

    with open(output, "r") as f:
        body = f.read()

    with open(output, "w") as f:
        f.write("/* Automatically generated by genconfig.py — DO NOT EDIT. */\n")
        f.write("/* Use 'cmake --build build -t menuconfig' to change. */\n\n")
        f.write("#ifndef CLI_CONFIG_H\n")
        f.write("#define CLI_CONFIG_H\n\n")
        f.write(body)
        f.write("\n#endif /* CLI_CONFIG_H */\n")

    print(f"Generated {output}")


def savedefconfig(kconf, output):
    """Save minimal defconfig with sorted entries and header comment."""

    kconf.write_min_config(output)

    # Read, sort, and rewrite with header
    with open(output, "r") as f:
        lines = f.readlines()

    configs = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("CONFIG_") or "is not set" in stripped:
            configs.append(line)

    configs.sort(key=lambda l: l.split("=")[0].split()[-1])

    with open(output, "w") as f:
        f.write("#\n")
        f.write("# Default configuration for mini-cli.\n")
        f.write("# Use 'cmake --build build -t savedefconfig' to regenerate.\n")
        f.write("#\n")
        f.writelines(configs)

    print(f"Saved {output}")


def main():
    src_dir = os.path.dirname(os.path.abspath(__file__))
    kconfig_file = os.path.join(src_dir, "Kconfig")
    dot_config = os.path.join(src_dir, ".config")
    defconfig = os.path.join(src_dir, "defconfig")

    os.environ["srctree"] = src_dir
    kconf = kconfiglib.Kconfig(kconfig_file, suppress_traceback=True)

    if os.path.exists(dot_config):
        kconf.load_config(dot_config)
    else:
        if os.path.exists(defconfig):
            kconf.load_config(defconfig)

    cmd = sys.argv[1] if len(sys.argv) > 1 else "genconfig"

    if cmd == "savedefconfig":
        output = sys.argv[2] if len(sys.argv) > 2 else defconfig
        savedefconfig(kconf, output)
    else:
        output = sys.argv[2] if len(sys.argv) > 2 else os.path.join(src_dir, "cli_config.h")
        genconfig(kconf, output)


if __name__ == "__main__":
    main()
