# Copyright 2026 Junbo Zheng
# SPDX-License-Identifier: Apache-2.0

# cmake/kconfig.cmake — Kconfig integration for CMake
#
# Provides:
#   KCONFIG_HEADER  - path to generated cli_config.h
#   CLI_PORT_SRC    - port layer source file based on .config
#   menuconfig      - cmake target for interactive config
#   genconfig       - cmake target to regenerate cli_config.h

set(KCONFIG_HEADER "${CMAKE_BINARY_DIR}/cli_config.h")
set(DOT_CONFIG "${CMAKE_SOURCE_DIR}/.config")
set(DEFCONFIG "${CMAKE_SOURCE_DIR}/defconfig")

# Generate .config from defconfig if not exists
if(NOT EXISTS "${DOT_CONFIG}")
    execute_process(
        COMMAND python3 -c "
import kconfiglib, os
os.environ['srctree'] = '${CMAKE_SOURCE_DIR}'
kconf = kconfiglib.Kconfig('${CMAKE_SOURCE_DIR}/Kconfig', suppress_traceback=True)
kconf.load_config('${DEFCONFIG}')
kconf.write_config('${DOT_CONFIG}', header='# Automatically generated by Kconfig — DO NOT EDIT.\\n# Use cmake --build build -t menuconfig to change.\\n')
"
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    )
endif()

# Generate cli_config.h
execute_process(
    COMMAND python3 "${CMAKE_SOURCE_DIR}/genconfig.py" genconfig "${KCONFIG_HEADER}"
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
)

# Custom targets
add_custom_target(genconfig
    COMMAND python3 "${CMAKE_SOURCE_DIR}/genconfig.py" genconfig "${KCONFIG_HEADER}"
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    COMMENT "Regenerating cli_config.h from .config"
)

add_custom_target(menuconfig
    COMMAND python3 -m menuconfig
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    USES_TERMINAL
    COMMENT "Running menuconfig"
)

add_custom_target(savedefconfig
    COMMAND python3 "${CMAKE_SOURCE_DIR}/genconfig.py" savedefconfig "${DEFCONFIG}"
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    COMMENT "Saving minimal sorted defconfig"
)

# Parse .config into CMake variables
# e.g. CONFIG_CLI_BUILD_EXAMPLES=y -> set(CONFIG_CLI_BUILD_EXAMPLES "y")
file(STRINGS "${DOT_CONFIG}" _config_lines REGEX "^CONFIG_")
foreach(_line ${_config_lines})
    string(REGEX MATCH "^([^=]+)=(.*)" _match "${_line}")
    if(_match)
        set(${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
    endif()
endforeach()

# Platform selection
if(CONFIG_CLI_PLATFORM_RTOS)
    set(CLI_PORT_SRC_FILE cli_port_rtos.c)
else()
    set(CLI_PORT_SRC_FILE cli_port_linux.c)
endif()
