# Copyright 2026 Junbo Zheng
# SPDX-License-Identifier: Apache-2.0
#
# Creates labels in GitHub.

name: Sync Labels

on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Manage Labels
        uses: amrivas/label-manager-action@v1
        with:
          labels_file: .github/labels.yml
          token: ${{ secrets.GITHUB_TOKEN }}